name: CI/CD Build and Publish Container Stack

on:
  push:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code Repository
      uses: actions/checkout@v4

    - name: Setup Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Linting Tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run Code Analysis Checks
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  build-and-push-images:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code Repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & Push Backend Container Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.backend
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/crag-backend:latest

    - name: Build & Push Frontend Container Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.frontend
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/crag-frontend:latest